### ISSUE TITLE
Line numbers break middle panel in Yazi v0.3.3

### ISSUE THREAD

**Issue by Anomalocaridid** [dedukun/relative-motions.yazi#11]
In Yazi v0.3.3, when setting `show_numbers` to anything but `"none"`, the current directory's panel breaks.

Example:
```lua
require("relative-motions"):setup { show_numbers = "relative_absolute" }
```

However, the plugin still works otherwise, including if `show_motion` is set as long as `show_numbers` is not set or set to `"none"`.

**Comment by dedukun** [comment]
Yeah this was already noted in https://github.com/dedukun/relative-motions.yazi/issues/1#issuecomment-2432714850 but thanks for creating a dedicated issue, the problem is that Yazi upstream changed the plugins API (in https://github.com/sxyazi/yazi/pull/1257 and https://github.com/sxyazi/yazi/pull/1863), and the latest commits that I did adapt the plugin to work with it.

Seeing that you are using Yazi v0.3.3, please use branch https://github.com/dedukun/relative-motions.yazi/tree/0.3.3 from the plugin (or if you are using `ya pack`, you can force the commit of the plugin like described [here](https://yazi-rs.github.io/docs/cli#package-manager)).

If that doesn't work, please let me know I will look further into it.

**Comment by Anomalocaridid** [comment]
Using that branch fixed it. Thank you!
